app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app.users:
    path:     /users
    defaults: { _controller: AppBundle:Home:browseUsers}

app.createWorkout:
    path:     /createWorkout
    defaults: { _controller: AppBundle:Home:createWorkout}

app.showWorkout:
    path:     /workouts/{id}
    defaults: { _controller: AppBundle:Home:showWorkout}

app.taskSuccess:
    path:     /success
    defaults: { _controller: AppBundle:Home:taskSuccess}

app.rateWorkout:
    path:     /rating/{id}
    defaults: { _controller: AppBundle:Home:rateWorkout}

app.showWorkouts:
    path:     /showWorkouts
    defaults: { _controller: AppBundle:Home:showWorkouts}

app.showWorkoutPage:
    path:     /showWorkoutsPage
    defaults: { _controller: AppBundle:Home:showWorkoutsPage}

app.showProfile:
    path:     /showProfile/{id}
    defaults: { _controller: AppBundle:Home:showProfile}

app.showComments:
    path:     /showComments/{id}
    defaults: { _controller: AppBundle:Comment:showComments}

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
