app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app.users:
    path:     /users
    defaults: { _controller: AppBundle:User:browseUsers}

app.createWorkout:
    path:     /createWorkout
    defaults: { _controller: AppBundle:Workout:createWorkout}

app.showWorkout:
    path:     /workouts/{id}
    defaults: { _controller: AppBundle:Workout:showWorkout}

app.showWorkoutPage:
    path:     /showWorkoutsPage/{page}/{sort}/{difficulty}/{search}
    defaults: { _controller: AppBundle:Home:showWorkoutsPage, search: 0}

app.showProfile:
    path:     /showProfile/{id}
    defaults: { _controller: AppBundle:User:showProfile}

app.showComments:
    path:     /showComments/{id}
    defaults: { _controller: AppBundle:Comment:showComments}

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
