app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app.regimes:
    path:     /regimes
    defaults: { _controller: AppBundle:Home:browseRegimes}

app.users:
    path:     /users
    defaults: { _controller: AppBundle:Home:browseUsers}

app.createRegime:
    path:     /createRegime
    defaults: { _controller: AppBundle:Home:createRegime}

app.showRegime:
    path:     /regimes/{id}
    defaults: { _controller: AppBundle:Home:showRegime}

app.taskSuccess:
    path:     /success
    defaults: { _controller: AppBundle:Home:taskSuccess}

app.rateRegime:
    path:     /rating/{id}
    defaults: { _controller: AppBundle:Home:rateRegime}

app.showRegimes:
    path:     /showRegimes
    defaults: { _controller: AppBundle:Home:showRegimes}

app.showRegimePage:
    path:     /showRegimesPage/{page}/{sort}/{difficulty}
    defaults: { _controller: AppBundle:Home:showRegimesPage}

app.showProfile:
    path:     /showProfile/{id}
    defaults: { _controller: AppBundle:Home:showProfile}

app.showComments:
    path:     /showComments/{id}
    defaults: { _controller: AppBundle:Comment:showComments}

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
